services:
  web:
    image: nginx:latest # We don't need to customize the image. Just pass the configuration to the Dockerfile.
    networks:
      - laravel
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro  # Mount the nginx.conf file directly
      - ${LARAVEL_APP_PATH}:/var/www
    ports:
      - "${NGINX_PORT}:80"
    environment:
      - NGINX_HOST=${NGINX_HOST}

  php-fpm:
    # For the php-fpm service, we will create a custom image to install the necessary PHP extensions and setup proper permissions.
    build:
      context: ../
      dockerfile: production/php-fpm/Dockerfile
      args:
        LARAVEL_APP_RELATIVE_PATH: ${LARAVEL_APP_RELATIVE_PATH}
    environment:
      - APP_NAME=TestApp
    networks:
      - laravel
    # The `depends_on` section tells Docker Compose to
    # start the database before your application.
    depends_on:
      postgres:
        condition: service_healthy
  
  php-cli:
    build:
      context: ../
      dockerfile: production/php-cli/Dockerfile
      args:
        # This is for flexibility of the example. Ideally, your context should be the root of your project.
        LARAVEL_APP_RELATIVE_PATH: ${LARAVEL_APP_RELATIVE_PATH}
    tty: true   # Keep the terminal open
    stdin_open: true  # Keep stdin open to attach to the container
    environment:
      - APP_NAME=TestApp
    networks:
      - laravel

  postgres:
    image: postgres:16
    restart: always
    user: postgres
    secrets:
      - db-password
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - laravel
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    networks:
      - laravel

networks:
  laravel:

volumes:
  postgres-data:

secrets:
  db-password:
    file: db-password.txt
